//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDIT
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> DISBURSEMENT { get; set; }
        public Nullable<int> COMMISSION { get; set; }
        public Nullable<int> INTEREST_RATE { get; set; }
        public Nullable<int> TERM { get; set; }
        public Nullable<int> CREDIT_TYPE { get; set; }
    
        public virtual CREDIT_TYPES CREDIT_TYPES { get; set; }
    }
}
